version: '3'
services:
  app-1:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - PORT=3000
      - MESSAGE=<h1>Hello there!</h1>
    ports:
    - 80:3000

  app-2:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - PORT=3001
      - MESSAGE=<h1>General Kenobi!</h1>
    ports:
    - 8080:3001